name: int_addr

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    strategy:
      matrix:
        python: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox pyinstaller
      - name: Run Tox
        run: tox -e py
      - name: Build binary with pyinstaller
        run: pyinstaller --onefile int_adder/int_adder.py
